# Generated by Django 4.1 on 2022-08-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
    ]
